name: Greek Heroes Pipeline 👷
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          check-latest: true
      - name: Install Dependencies
        run: yarn
      - name: Unit Test
        run: yarn jest
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
      - name: Upload app
        uses: actions/upload-artifact@master
        with:
          name: greek artifacts
          path: build/
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-16.04
    steps:
      - name: Download
        uses: actions/download-artifact@master
        with:
          name: greek artifacts
          path: build/
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build